name: Pull Request or Push

on: [push, pull_request]

jobs:
  ci:
    name: CI
    uses: salt-extensions/central-artifacts/.github/workflows/ci.yml@main
    permissions:
      contents: write
      pull-requests: read
